### ISSUE TITLE
Broken roadmap link in README 

### ISSUE THREAD

**Issue by mdigi14** [protectai/llm-guard#100]
**Describe the bug**
The link to roadmap in the README returns a 404.

**To Reproduce**
1. Click on the roadmap link in the README.

**Expected behavior**
Should return the latest roadmap.

**Screenshots**
<img width="927" alt="Screenshot 2024-02-20 at 10 28 19 AM" src="https://github.com/protectai/llm-guard/assets/35337224/bcf8715c-e71d-4cdd-af1c-255929b88c42">

**Comment by asofter** [comment]
Hey @mdigi14 , thanks for sharing it. I will remove mentions of the roadmap as in the ever-changing world of LLM Security, it's hard to keep it up-to-date for us. 

Short-term plan is to refactor the project a bit.
