### ISSUE TITLE
RuntimeError: Numpy is not available

### ISSUE THREAD

**Issue by jayita13** [protectai/llm-guard#115]
**Describe the bug**
RuntimeError: Numpy is not available

**To Reproduce**
Running on ```Windows 11``` and ```python 3.10``` ```numpy==1.22.3```
Code file -> https://github.com/protectai/llm-guard/blob/main/examples/openai_api.py

**Screenshots**
![image](https://github.com/protectai/llm-guard/assets/64038928/5a583242-2889-4e84-8d11-4568b3593083)

**Comment by nibedita6302** [comment]
Have you installed Numpy?

**Comment by jayita13** [comment]
numpy is already installed version ```numpy==1.22.3```, mentioned the same above earlier, please check
the issue is with internal python files where numpy is being used ```token_classification.py``` (used by ```anonymize.py``` & ```evaluate.py``` of llm-guard)part of ```transformers library```
line 302 ``` logits = model_outputs["logits"][0].numpy() ```
Please refer to the screenshot attached
