### ISSUE TITLE
Request to update tokenizers dependency to support Cohere LLM

### ISSUE THREAD

**Issue by ulan-yisaev** [protectai/llm-guard#143]
**Describe the bug**
`llm-guard` (version 0.3.13) depends on `transformers` (version 4.39.3), which in turn depends on `tokenizers` (versions >=0.14 and <0.19). However, `cohere` (version 5.5.0) depends on `tokenizers` (versions >=0.19 and <0.20). This version conflict causes dependency resolution to fail when both `llm-guard` and `cohere` are included in the same Llamaindex project.

**To Reproduce**
1. Create a new project with the following `pyproject.toml` dependencies:
   ```toml
   [tool.poetry.dependencies]
   python = ">=3.11,<3.12"
   cohere = "5.5.0"
   llm-guard = "0.3.13"
   ```
2. Run `poetry install`.
3. Observe the dependency resolution error:
   ```
   Resolving dependencies...
   Because llm-guard (0.3.13) depends on transformers (4.39.3) and transformers (4.39.3) depends on tokenizers (>=0.14,<0.19), llm-guard (0.3.13) requires tokenizers (>=0.14,<0.19).
   And because cohere (5.5.0) depends on tokenizers (>=0.19,<0.20), llm-guard (0.3.13) is incompatible with cohere (5.5.0).
   So, because api depends on both cohere (5.5.0) and llm-guard (0.3.13), version solving failed.
   ```

**Expected behavior**
`llm-guard` should be compatible with `cohere` (version 5.5.0) by updating its dependencies to versions that do not conflict, specifically bumping the `tokenizers` dependency to be compatible with `cohere`.

**Screenshots**
N/A

**Additional context**
To resolve this issue, it would be helpful if `llm-guard` could update its `transformers` dependency to a version that depends on `tokenizers` >=0.19 and <0.20, thereby avoiding the version conflict with `cohere`. This update would help ensure compatibility and smoother dependency resolution for projects using both `llm-guard` and `cohere`.

**Comment by asofter** [comment]
Hey @ulan-yisaev , thanks for the suggestion. I upgraded `transformers` version to the latest one.
