### ISSUE TITLE
Python 3.12 support?

### ISSUE THREAD

**Issue by alexs-forgood-ai** [protectai/llm-guard#150]
Hi, is there anything preventing from bumping max support version of Python to 3.12? Currently it is `>=3.9,<3.12`

**Comment by asofter** [comment]
Hey @alexs-forgood-ai , thanks for submitting this issue.

Previously, our dependencies didn't support v3.12, so we couldn't upgrade. Today, I tried again to see if there is difference, and all tests are running without issues. Therefore, the requirements were relaxed, and LLM Guard has a support of Python 3.12.

**Comment by alexs-forgood-ai** [comment]
Great, thanks! When would that go into release though?

**Comment by asofter** [comment]
It went to the 0.3.14 release.
