### ISSUE TITLE
How to suppress logging

### ISSUE THREAD

**Issue by brucewlee** [protectai/llm-guard#164]
how do i suppress logging

**Comment by asofter** [comment]
Hey @brucewlee , thanks for reaching out. Apologies for the delay.

We have a function which you can use to change the configuration of the logger: https://github.com/protectai/llm-guard/blob/main/llm_guard/util.py#L31

Here is example of how it's being used in the API: https://github.com/protectai/llm-guard/blob/main/llm_guard_api/app/util.py#L71

You can either send the output to some noop stream or change the log to only do it for errors
