### ISSUE TITLE
Why is this "my name is arjun" considered as PromptInjection?

### ISSUE THREAD

**Issue by shivably** [protectai/llm-guard#167]
input: `{
  "prompt": "my name is arjun",
  "scanners_suppress": [
        "BanCode",
        "BanCompetitors",
        "BanSubstrings",
        "BanTopics",
        "Code",
        "Secrets",
        "TokenLimit",
        "Toxicity"
    ]
}`
output:
`{
    "is_valid": false,
    "scanners": {
        "Anonymize": 1.0,
        "PromptInjection": 1.0
    },
    "sanitized_prompt": "my name is [REDACTED_PERSON_3][REDACTED_PERSON_4][REDACTED_PERSON_5]"
}`

API endpoint: http://127.0.0.1:8000/analyze/prompt

**Comment by asofter** [comment]
Hey @shivably , I think the reason is that it redacts before sending it to the prompt injection model for scanning. My recommendation is to put Anonymize scanner at the end, so it scans the real prompt. 

Also, there is /scan/prompt endpoint which doesn't redact but just analyzes
