### ISSUE TITLE
llm-guard pip not upgraded to latest code change of transformers update.

### ISSUE THREAD

**Issue by selvaebi** [protectai/llm-guard#174]
llm-guard pip not upgraded to latest code change of transformers update. pip llm-guard still points to transformers 4.41.2

**Comment by asofter** [comment]
Hey @selvaebi ! We upgraded all the dependencies.

**Comment by selvaebi** [comment]
pip install llm-guard latest , does not support transformers >= 4.43.0 onward which is needed by https://huggingface.co/meta-llama/Meta-Llama-3.1-8B.
