### ISSUE TITLE
Security layer for API

### ISSUE THREAD

**Issue by nxfi777** [protectai/llm-guard#74]
**Is your feature request related to a problem? Please describe.**
Anyone can access my API

**Describe the solution you'd like**
I would like to have a security layer such as a token/API key for authentication

**Describe alternatives you've considered**
Custom docker image, but that would mean sacrificing updates.

**Additional context**
N/A

**Comment by asofter** [comment]
Hey @nxfi777 , thanks for raising the feature request. We are planning changes to our API to introduce auth, observability and more features, so your request is very timely. I will keep you updated

**Comment by asofter** [comment]
Hey @nxfi777 , we added HTTP Bearer and HTTP Basic auth to the API. It's not yet deployed but will be by the end of this week
