### ISSUE TITLE
LLM_GUARD_API not working

### ISSUE THREAD

**Issue by knowitall12** [protectai/llm-guard#95]
**Describe the bug**
When deploying llm_guard_api we are unable to use following endpoints: /docs, analyze/prompt, analyze/output

**To Reproduce**
1. Deploy the llm_guard_api in docker container
2. try using localhost/docs

**Expected behavior**
API should give us the results of scanners and swagger ui.

**Screenshots**
![image](https://github.com/protectai/llm-guard/assets/152639815/e6ee2b4b-872f-4061-a46c-93abfcbc2059)

**Additional context**

**Comment by asofter** [comment]
Hey @knowitall12 , please remove `auth` from the config file, or you can pass `AUTH_TOKEN` environment variable, which you can use in `Authorization: Bearer TOKEN` header
