### ISSUE TITLE
Request for the API interface definition and sample implmentation codes

### ISSUE THREAD

**Issue by ajithbitspilani** [protectai/llm-guard#96]
Currently the LLM-Guard API is not exposing interface details in swagger UI.

I would like to see documentation of API POST interfaces and a best practice python sample code to integrate with existing chat applications.

Thank you.

**Comment by asofter** [comment]
Hey @ajithbitspilani , when you set `LOG_LEVEL` as `DEBUG`, it will open Swagger UI. Alternatively, it is also available in our documentation: https://llm-guard.com/usage/api/#schema
