### ISSUE TITLE
Scanners' speed, pulling up packages at execution

### ISSUE THREAD

**Issue by SamuelJanoska** [protectai/llm-guard#97]
Hi, I noticed that when i have llm-guard installed and running for the first time, some packages start downloading just as the API endpoint is called. That is several hundreds of MB and minutes (I took note at model.safetensors, 738MB and pytorch, 499MB). When these are installed, and second call is performed, it takes still about 10 seconds. I noticed the slowdown at printing 'Loaded regex pattern group_name=PO_BOX_RE' and 'Initialized classification model device=device(type='cpu')' Do you have any suggestions how to make the call in a second or two?
Applies for 0.3.4 and latest version.

**Comment by asofter** [comment]
Hey @SamuelJanoska , there are two issues you mentioned:
1. Model size. This can be improved by using different base model like distilbert but with accuracy tradeoff, or quantization with latency tradeoff.
2. Latency. For that, we recommend using ONNX versions which are optimized for the CPU: https://llm-guard.com/get_started/optimization/#onnx-runtime

Please let me know if you have further ideas on improvements.
